name: Export my notion workspace

on:
  schedule:
    - cron: "0 */12 * * *"  # Call the export every 1 hour
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: igor-kupczynski/notion-exporter@v1.0.2
        with:
          pages: "91b9c5e86c31459bb8f0ca4d831559a7"  # Pages IDs identified in (step 2)  
          output-dir: notion-backup
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
